### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by r7kamura** [r7kamura/sitespec#10]
- [x] Markdown example · Issue #5 
- [x] Replace my blog as an example · Issue #2 
- [x] GitHub Pages Integration · Issue #8
